apiVersion: v2
name: kubernetes-ingress-controller
description: A Kubernetes ingress controller built using ngrok.
version: 0.12.1
appVersion: 0.10.1
keywords:
  - ngrok
  - networking
  - ingress
  - edge
  - api gateway
home: https://ngrok.com
sources:
  - https://github.com/ngrok/kubernetes-ingress-controller
icon: https://ngrok.com/static/img/brand/ngrok-favicon.svg
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
