# 1. Copy this file to ./config.yaml
# 2. Set you unique FQDN in the "value" field below
- op: replace
  path: /spec/rules/0/host
  value: <UNIQUE SUBDOMAIN 2>.ngrok.io
# e2e-expected: HTTP/1.1 404 Not Found