name: Release

on:
  push:
    branches:
      - main
      # TODO: Should be scoped to tag pushes eventually

jobs:
  docker_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ngrok/ngrok-ingress-controller:latest

  helm_bump_version:
    needs: docker_release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Read Helm Chart Version
        id: helm_chart
        uses: jacobtomlinson/gha-read-helm-chart@master
        with:
          path: helm/ingress-controller

      - name: Increment Semver Patch-level
        id: next_version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: "${{ steps.helm_chart.outputs.version }}"

      - name: Update Chart version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "helm/ingress-controller/Chart.yaml"
          find: '(?m)^version: .*$'
          replace: "version: ${{ steps.next_version.outputs.patch }}"

      - name: Commit Chart.yaml version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment (patch-level) chart version

  helm_release:
    needs: helm_bump_version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: helm
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
